### PR TITLE
utflower fix

### PR DESCRIPTION
**Pull request by drgrib**
Fixes `utflower` calls for `NULL` `notes.ZTEXT` values and improves error checking.

### CODE REVIEW

**Comment by drgrib** [comment]
@kudrykv This build works for me. I have no idea why. I tried very large sizes for `utflower` in a test file and they never failed. Let me know if you think this will still get you decent results, though.

**Comment by kudrykv** [comment]
@drgrib here's an idea. What if, instead of changing it back, add the new change as an additional condition?
```sql
...
AND (
	utflower(note.ZTITLE) LIKE utflower('%%%s%%') OR
	lower(note.ZTEXT) LIKE lower('%%%s%%') OR
	utflower(note.ZTEXT) LIKE utflower('%%%s%%')
)
...
```

This way one or both conditions would work, and cover more cases.

**Comment by drgrib** [comment]
@kudrykv That is a great idea and I tried it but it breaks the build again. Which is evidence to me that running `utflower(note.ZTEXT)` is crashing the `sqlite3` driver somehow and it is recovering from it by simply returning a null result instead of an error.

**Comment by drgrib** [comment]
Alright, maybe it isn't crashing it because this returns results:
```
	AND (
		utflower(note.ZTITLE) LIKE utflower('%%%s%%') OR
		utflower(note.ZTEXT) LIKE utflower('%%%s%%') OR
		lower(note.ZTEXT) LIKE lower('%%%s%%') OR 
		TRUE
	)
```
But without that `OR TRUE` in there, I get nothing. I am so baffled by this...

**Comment by kudrykv** [comment]
I'm puzzled 😕
Should that just be reverted till the previous version?
Out of curiosity, how large is your largest note?

**Comment by drgrib** [comment]
I will at least use this version, which is partially functional because it can compare titles.

But that `OR TRUE` situation has me thinking: I have *a lot* of code in the `ZTEXT` of my notes. I suspect I have code in a note is getting injected into the query somehow because `utfLower` has no escaping. I suspect the code is being placed directly into the query by the `RegisterFunc`. The reason I think this is that I can get `utflower(note.ZTEXT)` to work if I replace the return value of `utfLower` with a static string instead of some version of `s`. I'll keep testing for a way to escape it a bit longer before giving up.

**Comment by kudrykv** [comment]
> The reason I think this is that I can get `utflower(note.ZTEXT)` to work if I replace the return value of `utfLower` with a static string instead of some version of s.

I'm not sure that's the reason. The function receives the value from `note.ZTEXT`. The value is not injected in query, but rather should be handled by the sqlite. Though now as you mentioned it, there actually are a potential issue with `('%%%s%%')` construct -- it is a string interpolation. I see the text is sanitised manually, and I wonder about this approach as opposed to passing arguments into `sql.Query` function.

Nevertheless I'm very thankful for you investing time in this.

**Comment by drgrib** [comment]
I still can't rule out an injection at this point given what I'm seeing. I did try direct query argument with no `%%%s%%%` in the code as you suggested. But I get the same null results with

```
		utflower(note.ZTITLE) LIKE utflower('%'||$1||'%') OR
		utflower(note.ZTEXT) LIKE utflower('%'||$1||'%')
```

and

```
		utflower(note.ZTITLE) LIKE utflower('%'||$1||'%') OR
		utflower(note.ZTEXT) LIKE utflower('%'||$1||'%') OR
		lower(note.ZTEXT) LIKE lower('%'||$1||'%')
```
Still at a loss as how to handle this aside from the partial solution that is in the PR now.

**Comment by drgrib** [comment]
Solved it @kudrykv! So here is what happened: `lower` can [receive NULL values and return NULL](https://docs.oracle.com/javadb/10.8.3.0/ref/rrefsqlj42049.html).

However, `RegisterFunc` functions like `utflower` [cannot receive NULL values](https://godoc.org/github.com/mattn/go-sqlite3#SQLiteConn.RegisterFunc). They can only receive strongly typed values.

Apparently my old, long-lived Bear `db` contains some `NULL` values for `ZTEXT` and they were causing errors for calls to `utflower`, which I discovered when I added better error checking for the `LiteDB.Query` function.

So we are fully functional now with `utflower` used in all queries in place of `lower` with a preemptive `note.ZTEXT IS NOT NULL` check. I'll post the new binary file after merging.

**Comment by kudrykv** [comment]
@drgrib that is awesome!

Thank you!

**Pull request merged**
